### ISSUE TITLE
[idea] Add a vote on game settings preset instead of host choosing

### ISSUE THREAD

**Issue by kacperpl1** [ash47/LegendsOfDota#108]
I just thought it could work if instead of host choosing all settings we could have those few presets for how many skill slots are enabled and what type of skills you can pick. Just a thought, maybe not important if whole game standardization / captains mode kicks in.

**Comment by ash47** [comment]
LoD has game mode voting built into it, it gives everyone an option picking
interface and it averages the choices, it really sucks

**Comment by kacperpl1** [comment]
If it's about multiple settings as now it's obvious it will suck. I mean if you make few presets you could vote for lets say one of 5 presets and it could work somehow. Anyway that still leaves the chance of people disconnecting when they don't want to play the voted settings.

**Comment by chrislafeken** [comment]
If it were possible I think the BIGGEST way to reduce people leaving is to have options for what the game is gonna be like picked during lobby instead of after going thru the time of loading and stuff. Then people knwo what they're getting in to.

**Comment by ohos** [comment]
settings voiting is absurd, because when you want play WTF, as host you can just make a game you want, but without host choosing you can't

better idea would be just split game mode into separate maps like Overthrow, if you download this mode you can choose from 1 of 3 maps

solo
duo
trio

of course LOD has much more settings and it's impposible to split them all, but it would be perfect to split at least most popular settings like:

1. all pick, all random, single draft (3 types)
2. wtf = yes/no (2 types)
3. number of spell slots 4,6,12 (3 types)

then it would be 18 total combinatios because 3*2*3=18

**Comment by ash47** [comment]
This is probably not going to happen.
