### ISSUE TITLE
[Suggestion]Creeps with thirst

### ISSUE THREAD

**Issue by SunbleachedAngel** [ash47/LegendsOfDota#121]
Ash, please disable thirst for creeps because they become so fucking crasy and can win game by their own.

**Comment by chrislafeken** [comment]
You could host ban thirst so nobody can add thirst as a creep skill. 
Honestly, there's a lot of abilties that are really strong on creeps. Mainly because having an ability on a creep means having it on 5 people all ready to attack you. 5 creeps all throwing down fury swipes, or 5 creeps with meepo's passive, or giving them bashes. honeslty it gets a little crazy when they gang up on ya. Give them grow and watch them push towers hard

**Comment by ash47** [comment]
I forgot you could even add abilities to creeps, lol, thirst is currently removed from the game, so, I guess this is fixed XD
