### ISSUE TITLE
Few modifications this game really needs to be enjoyable...

### ISSUE THREAD

**Issue by Ech00** [ash47/LegendsOfDota#143]
Just few things really need tweaks... Played the concept a lot at warcraft 3 and there's few things this mode really needs and few bugs/glitchable things also i saw in few first games.

Tweaks:

-Witchcraft+Low cd spells. Take it with antimage blink for example it's really way too overpowered with only 1 second cooldown you can almost evade every possible disable in the game... Consider same on other very low cd spells...

- Morph should be considered as 1 skill set and not 2 separate skills in the pick phase

-Intelligence gain should be skill contained (glaives of wisdom), not hero contained... Makes everybody pick silencer as it's a hero with "bonus" quite unfair actually...And boring to see same hero everywhere.

Bugs/glitchable:

-Power treads (skill not item) triggering aftershock or something like that? Just madness... Played a game where a guy trigger aftershock with no cooldown or manacost at all...<-This really needs fix

- Overpower on ranged heroes start to count projectile limit after 1st prjoctile hit the target.. So with take aim + overpower+oracle as hero (low BaT) the maximum attack speed is more like 12-15 attacks than 6...

Ech0

**Comment by Jexah** [comment]
Your point on Witchcraft is valid and this will be addressed by adding Witchcraft to the OP Skills category.

Morph has been discussed. Originally it was implemented the way it is now due to technical limitations, although it has proven to be balanced. A change is not required, but may be discussed.

Intelligence gain will never be part of Glaives of Wisdom, unless Valve change it back. For clarification, this is a balance decision and not a technical limitation. Disabling Silencer by default is being considered.

Items as skills are currently not balanced, and probably never will be. If you want balance, don't enable items as skills.

The mechanics relating to Overpower and ranged heroes are one of many unique mechanics in the game, and these are part of what give LoD its character. There are many, many interesting mechanics and interactions you can discover, and this is one of them. It is not imbalanced so won't be changed.

If you would like to discuss any of these points further feel free to follow up.

**Comment by Ech00** [comment]
Alright, that sums it up :) Glad for fast reply.

I'm not against the character of LoD. After all it's the diversity what makes it so special, been playing the old school version for years. And here's really lots of mechanical differences and so far i'm mostly impressed :+1: 

Okay so all i need then is a good hoster and regular modes. So OP skills and items should never be picked. Aftershock+Items skill is just retarted..I just don't understand the concept enabling items as skills in first place..That's what the shops are for.

I would say then ban silencer as it simply destroys the diversity and people always pick it since it's a carryish by model...

And for the mechanics question i don't mind if it stay like this :) Hell it's just really good combination actually with overpower+takeaim+impetus...Wonder does totem buff stay until 1st projectile lands... I just simply thought it wasn't intented as the skill itself clearly says 6 hits :)

Ech0

**Comment by Jexah** [comment]
Like I said, there are many neat tricks, and I recommend playing a bit by yourself and trying out different skill combinations, seeing if you can find any. I won't spoil a lot of them, as finding the interactions is most of the fun :)

The game mode is balanced around (mostly) default settings, and most of the other options are simply things that Ash felt like playing once or twice. Items as skills as an example, was more like "Hey, wouldn't it be cool if we could select items as skills? I wonder how it would play out." than "Hey let's add items as skills because it's balanced."

This mindset is reflected in Frota. Over 90% of the options are not balanced, but are just there to give more options for those who would like to try things out.

In my opinion, most of the settings should not be changed to ensure a balanced game. Ash is working on streamlining the game so it is much easier and faster to get into a balanced game and start playing.

Enchant Totem buff works as you wonder. So do other, similar skills.

Thanks for taking the time to explain your opinions nicely. It's refreshing to see somebody correctly communicate their ideas.

**Comment by Veroalla** [comment]
Summary:
Witchcraft too op - put into OP: solved
Both Morphs can't be in 1 slot, that's how it works: solved?
Silencer steals int - now it's bound to glaives: solved
Enchant totem, jinada, overpower on ranged heroes OP: this can stay? It's LOD

So I guess you close this issue if you like, I don't see a solution for the last one.

**Comment by Ech00** [comment]
Yeah thanks, i just mentioned morph like this as it is so in old version of LoD (warcraft 3) as you pick one skill you get both str active and agi agtive so you don't waste too many skill slots if you decide to go for morphing build that can go both ways.

And simply wanted to notify about the overpower "bug" as in description it say how it work but on fast Base attack time heroes and range you can actually cheat few extra hits :D But i like these things on LoD, i just wanted to say if it's something unplanned and you wished to change it personally i like these "glitches better" :)

Closing it now
