### ISSUE TITLE
Bug report issue.

### ISSUE THREAD

**Issue by rawinza555** [ash47/LegendsOfDota#154]
There's a list of thing I found that kinda broken or not really legit
In normal game
- <s>even though we can't pick it directly, Spirit bear's return and BS's thirst can be picked through random option in a drop down menu when right click in an empty skill box</s>
- Life drain with aghanim scepter remove cooldown which trigger aftershock. I believe skywrath's ult work the same way
- range hero when using overpower sometimes launch the attack more than what it supposed to be
- <s>Tempest double sometimes cause the game to crash when using with some skills, one of them is visage ult. (But I haven't seen this for a while. It occurred like 3-4 weeks ago)</s>
- <s>war drum aura and dragonhide aura come with spell immunity. Even though spell immunity is gone if the hero is killed.</s> 

In multicast madness 
- <s>infest - multicasted infest sometimes make the hero infest to the ground when there's not enough target available in the area.</s>
- <s>Pudge's hook - sometimes it doesn't drag a target to the hero</s>
- <s>those consumable item like tango, clarity potion - not sure if u already fix it all but I sometimes lose all 4 tangoes in just one click</s>

**Comment by ash47** [comment]
Dearly noted, will work to fix some of these in the near future XD

**Comment by ash47** [comment]
Fixed a double of the issues, crossed them out

**Comment by ash47** [comment]
@Jexah thoughts on those troll combos?

**Comment by Veroalla** [comment]
Aftershock and ball lightning also causes you to stunlock. Combine it with burrow and you're untouchable :)

**Comment by Jexah** [comment]
Aftershock and Ball Lightning or Burrow should be in troll combos list already.

The ancient auras need a bit more wear and tear. There is a bug where they give you magic immunity when you spawn which disappears after you die. Once that bug is fixed, we'll see how it goes.

I have played against Life Drain with Aghanim's Scepter, and it's pretty rubbish. Needs an insane amount of mana to actually make it work. Can work with Essence Shift, but other people can still kill you and you're paying 3 skills and 4.2k gold for it to actually work. Seems pretty balanced. Same deal with Skywrath's Ult.

Ranged hero when using Overpower gets more than 6 attacks (if attacking from range). This is expected behaviour based on the mechanics of the game, and since 2013 has been an intended mechanic in LoD.

Summary: 

Fix magic immunity bug on Ancient auras, and see how it goes.

**Comment by rawinza555** [comment]
magic immune still there

**Comment by ash47** [comment]
Most of these issues fixed up in the new UI branch :)

**Comment by ash47** [comment]
I've fixed all the major ones, those other ones are kind of "not issues" in my eyes, that's just how the skills interact with each other, I'll leave it open as my opinion might change and i may fix stuff up :)

**Comment by ash47** [comment]
I have fixed the issues that we consider to be issues.
