### ISSUE TITLE
Issue with selecting hero

### ISSUE THREAD

**Issue by Veroalla** [ash47/LegendsOfDota#201]
Almost all games have someone ragequit when getting a hero they don't want.
Because it's not entirely obvious when you should pick your hero. And you can't even repick as you could in the old LOD. The final review screen is utterly useless if you can't change ANYTHING.

It's very annoying that it's in the same screen as picking skills, it should be a separate step AFTER picking spells, this would make more sense. (for example picking hero in review screen?)

**Comment by TheRisen41** [comment]
I second this. Hero picking should be after skill picking.

**Comment by Jexah** [comment]
The issue here, is that some builds require certain heroes, and if you pick your skills for a specific hero, then realise it's banned in the next phase, you can't go back and change your skills. 

In general, picking your hero at the same time you pick skills is good, currently it just needs some refinement.

**Comment by ash47** [comment]
I have added a message that tells players they need to pick their HERO AND ABILITIES!

I will also add a warning that appears once the 30 second mark is hit.

I will also consider giving every player a random hero to begin with, so they know what is going on @Jexah
