### ISSUE TITLE
Walrus punch can miss

### ISSUE THREAD

**Issue by XAgent1990** [ash47/LegendsOfDota#282]
As said in the sideinfos of the ability "Walrus punch can't miss" but atm, it can

**Comment by ash47** [comment]
If this is the case, the best I can really do is add a warning to say that it may miss if tusk isn't your hero.

**Comment by darklordabc** [comment]
Yeap, Walrus Punch can miss, and it also misses on Tusk.
![puncer2](https://cloud.githubusercontent.com/assets/16277198/15159798/bf41a972-1739-11e6-9763-c906bf8489ec.gif)
Turns out this is a bug in Dota 2, not LoD. 
[https://www.reddit.com/r/DotA2/comments/4h5x98/tusk_walrus_punch_broken_since_687/?sort=new](https://www.reddit.com/r/DotA2/comments/4h5x98/tusk_walrus_punch_broken_since_687/?sort=new)
