### ISSUE TITLE
would be nice to show ban/pick timer and make it's default time to be set by host

### ISSUE THREAD

**Issue by ohos** [ash47/LegendsOfDota#72]
would be nice to show ban/pick timer always somewhere instead of that "show option" button, because for some people it's really not clear what happening while top timer freezed on 0:59 and make it's default time to be set by host

**Comment by kacperpl1** [comment]
I think that picking settings by host and banning in general is a bad idea slowing down the game launch which ends up with people leaving the match. I'd rather have settings and bans decided by ash/discussed in the community as stated in https://github.com/ash47/LegendsOfDota/issues/68

**Comment by ohos** [comment]
it's only slow because time limit too long, there's 300 seconds on ban 5 abilities, lol? to decide needed not more then 30 sec for all 10 people, that's why i'm talking here about showing timer and allowing change it's default value and around 300 more on pick, it's 10 minutes

when i host i would like set it to 30 sec ban and 90 pick, so it won't be soo long, 2 minutes and game begin, who wasn't too quick - his own problems

**Comment by kacperpl1** [comment]
Rather than banning skills I think it would be better to limit skills to one player per skill so even if there's a trolling combo you don't have to for example fight whole team of invis nukers countering wards.

I think AD queue system works quite well - only needs adding heroes to pick and all skills to pick from rather than random batch like it now is.

That's the whole problem of LoD - match of AD is between 35 and 50 minutes while you get boosted and finish the whole thing in 15 minutes even with all those additional towers because the team that picked worse is crushed fast. It has completely different dynamic than normal/AD games because of that. Until that is fixed LoD cannot become a mainstream mode.

**Comment by ohos** [comment]
nice idea too, thought about it already, maybe good idea to specify hero count and then select which heroes give their abilities to choose

**Comment by kacperpl1** [comment]
Splitting stuff to pick between players like in single draft? That's not what I mean. If you played some AD, you know that thanks to queue people will try to counter other players picks by breaking their trolling combo's simply by picking stuff that this player needs. It's because of the queue you have the time to focus on what others pick. In LoD everyone stays focused on making his own awesome combo blindly wishing noone else will get something more OP. Such system will end up with people finding the most OP combo's possible and winning simply by pick and games will end up the same over and over. Single picking skills(which blocks picking the skill by other players) with queue simply works well and maintains some randomness in matches. What AD sucks in is the amount of skills to pick from and getting random hero that doesn't always match what you can pick. The optimum is something in between LoD and AD ad I think IF the target of this mod is to get mainstream then it needs to be optimal.

**Comment by ohos** [comment]
oh if you mean draft instead of "all pick together" then yes, i like this way

but in LoD still possible bans, so expirienced people may ban overpowered combos too

**Comment by kacperpl1** [comment]
yeah, but bans in mode that doesn't penalize leaving mean additional time that will encourage players to drop. What we need is going into picking phase as fast as possible like in AD.

There is also simple fix for making overpowered combo's - only one ultimate and 3 normal skills like in AD - if you have 6 skills then there's so much stuff you can do that your enemy can't keep up with the stuff you're doing. and both sides focus then on spamming shit rather than playing tactical. 

Think about it - while AD is criticized for bugs and favouring first player to pick, all other stuff makes it well balanced. LoD on the contrary is simply a banana mayhem.

**Comment by ash47** [comment]
This will be rectified with the new UI, once it is completed.

**Comment by ash47** [comment]
This issue is no longer needed.
