### ISSUE TITLE
new option - random passive skills for every tower

### ISSUE THREAD

**Issue by ohos** [ash47/LegendsOfDota#73]
Hi, would be nice to have mode "random passive skills for every tower".

**Comment by ash47** [comment]
as in, each tower gets it's own set?

**Comment by ohos** [comment]
yeah :D

but if you gonna make it be sure to roll from only passive skills since towers can't have mana and won't cast any active spells even withut mana (just tested a day ago), also this option can have additional options like

roll number abilities from X to Y, for example to let each tower have own set between 1 and 3 abilities (6 max of course)

**Comment by ash47** [comment]
Originally you could activate active spells on the towers, was amazing, until one day someone put Pudge rot on, and it killed all their towers XD

**Comment by ohos** [comment]
oh lol i didn't know player could controll tower abilities, so if towers can use abilities without mana then it's okay to keep them in roll, bur just fix rot, make tower invincible to self damage because there's huskar's arrows that drain hp for each shot, so with flak cannon or multyshot tower die fast as well lol

**Comment by ash47** [comment]
I changed it back so players cant anymore, it becomes too OP, there was
even a period when towers had mana :)

**Comment by kacperpl1** [comment]
The problem with random abilities for towers or creeps is that both teams should have equal abilities - otherwise it breaks the game.

Apart from the randomizing abilities I think that you could think about some tweaks with towers like:
- Adding some regen when not attacked or attacking like the one from tranquil boots
- Adding splash damage + making projectiles die out of attack radius so they don't follow players.
But that's just something that could be done in general to tweak towers.

**Comment by ash47** [comment]
This won't be added.
