### ISSUE TITLE
[request] advanced standart ability draft

### ISSUE THREAD

**Issue by ohos** [ash47/LegendsOfDota#77]
would be nice to make advanced standart ability draft mode with following changes:

phases:

1. each player select from X to Y heroes
2. players one by one on each team start banning heroes from pool of all selected heroes to reduce overall hero amount to N or ban some amount of abilities from these heroes to reduce ability amoun to M
3. normal AD rules (would be nice to tweak options, like seconds per pick, seconds pause between round and so on, or make presetted settings like "fast picks: 120 seconds total", "normal picks: 240 seconds total", "slowpoke picks: 10 minutes for true slowpokes xD"
4. one by one per team players pick base hero to hold abilities (i have ideas how extend this to make pick/bans if you like)

**Comment by ohos** [comment]
as option to pick changing order maybe fine to, in standart AD starting round man and ending pick twice in a row, would be better let option to remove it and let each round start always by first player or random

**Comment by ohos** [comment]
sure such mode can become mainstream to replace original ugly ability draft, who know maybe one day tournaments add this mode :P

i won't wast too many time building this on my own because i focused on UE4 and will keep it, but i can help test and suggest things

**Comment by ash47** [comment]
Probably won't do this, I have a much cooler idea though, think captin's mode, but for LoD ;)

**Comment by ohos** [comment]
captain mode really cool, just do it! :D

**Comment by kacperpl1** [comment]
I oppose to the captain's mode if it's to be the default mode - people will keep leaving when they don't like what they've been assigned by the captain.

I'd like it to be close to AD queue because in its own way it works balancing and pacing the picking system where everyone focuses on what others take. 

My general tip for you at this point of changes - as much as possible force your own default optimal configuration, overpowered and bugged skill bans. This works in favour to limiting rage quits in two ways - first as I stated before - limiting the amount of wait till picking begins and secondly limiting rage quits caused by unwanted settings - i.e skill ban wastes someone's idea what to build or host sets up some stupid config like 12 spells to pick. People will leave the match to find another one with better settings unless you make it a standard thing.

Secondary tip - for making people stay in game - think about balancing the picking system. For example enemy picks should be visible and swapping skills should be disabled - this way you can try to counter enemy combo's rather than jumping in and realising there was this one seriously OP build which whole enemy team took.

If you have other idea how to make it work then please share it with us, we'll give some feedback.

**Comment by ash47** [comment]
You can see enemy picks by enabling the option.

I've been developing this game mode for, I would estimate, over two years
now, and only now that common people are playing via reborn, has banning
become an issue, it was flawless before now.

Of course captains mode won't be default.

I'll consider making 0 bans the default.

**Comment by kacperpl1** [comment]
Yeah, I know - when people matchmaked it the hard way they didn't want to leave cause this kind of game happened not often. But now it's different, you gotta think about maintaining people during the match.

So far I haven't played a single game with full squad/no ragequits due to:
1) long banning/picking time
2) Imba combo and ragequits on first blood
3) stupid settings picked by host making creeps with random ablities push whole lanes or 12 abilities making the casting combo's hard because of toggle button etc.

What I mean is - You should find the most optimal settings and make them forced default. Maybe you could go with the different presets using the map select like in Overthrow which has 5v5 3v3v3 and 2v2v2v2v2. This way you could let people decide what preset settings they want to play by making a standarized mode and a custom one. I bet the standarized would be always populated :)

**Comment by ash47** [comment]
The issue being, ,that means shipping 70MB+ per preset :/

**Comment by kacperpl1** [comment]
Yeah, that's a pain, but that's only if there's no hack way to use same map file and different launch script. Also I think going for 1) standarized + 1 customizable would be enough to prove people will go for standarized mode rather than wait for custom matches unless they get their own premade 5v5 and want some fun

**Comment by ohos** [comment]
i have an idea how solve mode searching

for example you have current LOD and captain's draft, these 2 maps really differ too much, so you can make 2 separate castom games, like LOD and LOD captain's draft because people can't filter games or something else if it would be only 1 custom game

**Comment by ash47** [comment]
I know, I can ship a seperte version for each option combination! 4 x 4 x
12 x 12 x 12 x 12 x 2 x 2 x 2 x 3 x 2 x 2 x 2 x 2 x 2 x 2 x 2 x 2 x 2 x 3 x
2 x 12 x 12 x 10 x 8 x 2 x 2 x 2 x 2 x 2 x 2 x 2 x 2 x 5 x 8 x 4 x 4 x 4 x
4 = 738, 702, 928, 879, 445, 606, 400 addons I need to ship, if I start
now, i might be done by the time half life three is at E3 :)

**Comment by ohos** [comment]
lol, no i don't mean every single combination, sure separating LOD and Captain's draft LOD would be really enough, but if you really want go futher, then it's better separate all pick, all random, single draft - these mods, because they really make much difference

**Comment by kacperpl1** [comment]
But seriously - we're talking about making two separate modes/maps to split standarized version for common people randomly matchmaked from fully customizable mode for premade matches. Wasting 70 megs on that unless there's hack for this sounds like a good temporary plan.

Again Ashe, can you explain how you see that captain's draft mode working with spells? You want the captain to select heroes for the pool of skills?

**Comment by ohos** [comment]
of course LOD has much more settings and it's impposible to split them all, but it would be perfect to split at least most popular settings like:

all pick, all random, single draft (3 types)
wtf = yes/no (2 types)
number of spell slots 4,6,12 (3 types)
then it would be 18 total combinatios because 3 * 2 * 3=18

**Comment by kacperpl1** [comment]
The idea is to have a standardized mode without host selecting/voting on settings that would differ rules for each match.

I'm still opting for two modes - standard and custom and if you still want to fix the custom modes then there can be some simplifications in the amount of settings.

For the standard mode: depending on how ashe wants to make the system of picking I'd like to have 4 normal spells + single ultimate unless there's a queue with unique spell picking like in AD which would prevent building too OP ultimate combos. I think its better if you get the chance to pick some nice op stuff but the enemy counters you rather than having no chance to pick troll combo's and at the same time not having any chance to counter what enemy is trying to build.

**Comment by ash47** [comment]
This has partially been implemented, this issue no longer needs to exist, it will roll out when it's ready.
